main_timer:
  rate: 20.0 # [Hz]

diagnostics_timer:
  rate: 10.0 # [Hz]

future_check_timer:
  rate: 10.0 # [Hz]

# planning
planning_tree_resolution: 1.00 # [m] voxel edge size

euclidean_distance_cutoff: 1.2 # [m]
safe_obstacle_distance: 1.2 # [m]

distance_penalty: 1.0
greedy_penalty: 1.0

max_waypoint_distance: 0.0 # [m] // or set negative for no padding
min_altitude: 0.0 # [m]
max_altitude: 3.0 # [m]
unknown_is_occupied: false
replan_after: 1.0 # [s]

timeout_threshold: 2.0 # [s]
time_for_trajectory_generator: 1.0 # [s]

# visualization
points_scale: 0.22
lines_scale: 0.02
