main_timer:
  rate: 20.0 # [Hz]

future_check_timer:
  rate: 5.0 # [Hz]

# planning
planning_tree_resolution: 1.00 # [m] voxel edge size

euclidean_distance_cutoff: 1.2 # [m]
safe_obstacle_distance: 1.5 # [m]
distance_penalty: 1.0
greedy_penalty: 1.0
endpoint_tolerance: 2.0 # [m]
max_waypoint_distance: 3.0 # [m] // or set negative for no padding
min_altitude: 0.9 # [m]
unknown_is_occupied: false
replan_after: 1.0 # [s]

timeout_threshold: 2.0 # [s]
time_for_trajectory_generator: 0.3 # [s]

# visualization
points_scale: 0.22
lines_scale: 0.02
