# planning
euclidean_distance_cutoff: 1.2 # [m]
safe_obstacle_distance: 1.0 # [m]
distance_penalty: 0.5
greedy_penalty: 1.0
endpoint_tolerance: 0.3 # [m]
planning_tree_resolution: 0.4 # [m] voxel edge size
timeout_threshold: 2.0 # [s]
max_waypoint_distance: 4.0 # [m]
unknown_is_occupied: false

# visualization
points_scale: 0.22
lines_scale: 0.02
